
{
"swagger": "2.0",
"info": {
    "version": "1.0.0", 
    "title": "Video Game API",
    "description": "My User Project Application API"
},
"host": "localhost:3000",
"basePath": "/",
"consumes": ["application/json"],
"produces": ["application/json"],
"paths": {
    "/allgames": {
        "get": {
            "summary": "Lists All Games",
            "responses": {
                "200": {
                    "description": "OK",
                    "schema":{
                        "type": "object",
                        "example": {
                            "name": "Acid Drop",
                            "platform": "Atari",
                            "developers": "Dennis Kiss[11]",
                            "publisher": "Salu Ltd",
                            "releaseDate": "1992",
                            "genres": "Strategy",
                            "notes": "PAL-only; puzzle game; last game released. Atari 2600s stopped being manufactured"
                        }
                    }
                }  
            }
        },
        "post": {
            "summary": "Creates New Entry to All Games",
            "consumes": "application/json",
            "parameters":[ 
                {
                 "in": "body",
                 "name": "body",
                 "schema": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "String"
                        },
                        "platform": {
                            "type": "String"
                        },
                        "developers": {
                            "type": "String"
                        },
                        "releaseDate": {
                            "type": "String"
                        },
                        "genres": {
                            "type": "String"
                        }
                    }
                 }
                }
            ],
            "responses": {
                "201": {
                    "description": "Created",
                    "schema": {
                        "type": "object",
                        "example": {
                            "name": "Super Smash Bros",
                            "platform": "Switch",
                            "releaseDate": "Oct 13, 2020",
                            "developers": "Nintendo",
                            "genres": "['Action', 'Fighting', '2D']"
                        }
                    }
                }
            }
        }
    },
    "/allgames/{name}": {
        "get": {
            
        }
    },
    "/allgames/{id}": {
        "put": {

        },
        "delete": {

        }
    },
    "/atari": {
        "get": {
            "summary": "Lists Atari Games",
            "responses": {
                "200": {
                    "description": "OK",
                    "schema":{
                        "type": "object",
                        "example": {
                            "name": "Acid Drop",
                            "platform": "Atari",
                            "developers": "Dennis Kiss[11]",
                            "publisher": "Salu Ltd",
                            "releaseDate": "1992",
                            "genres": "Strategy",
                            "notes": "PAL-only; puzzle game; last game released. Atari 2600s stopped being manufactured"
                        }
                    }
                }  
            }
        }
    }
    },
  "definitions": {
    "allgames": {
      "required": ["name", "_id"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true
        },
        "name": {
          "type": "string"
        },
        "platform": {
          "type": "string"
        },
        "books": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "amount": {
                "type": "number"
              }
            }
          }
        },
        "companies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}